import { PokerScenario } from "./types";

function scenario(
  partial: Omit<PokerScenario, "source"> & { source?: PokerScenario["source"] }
): PokerScenario {
  const freqs = partial.recommended;
  const total = freqs.reduce((s, r) => s + r.frequency, 0);
  if (Math.abs(total - 100) > 0.01) {
    throw new Error(`Scenario ${partial.id} frequencies sum to ${total}, not 100`);
  }
  return { ...partial, source: "Trackdown training scenario" };
}

export const POKER_SCENARIOS: PokerScenario[] = [
  scenario({
    id: "ps-01",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "BTN",
    stakes: "$1/$2",
    heroCards: "Ah Kh",
    board: "—",
    potSize: 3,
    actionHistory: "Folds to hero on the button.",
    availableActions: ["fold", "raise"],
    recommended: [
      { action: "fold", frequency: 5 },
      { action: "raise", frequency: 95 },
    ],
    preferredAction: "raise",
    explanation:
      "AKo on the button facing folds is a clear open. Training scenario recommends raising for value and to steal blinds.",
    concepts: ["Preflop aggression", "Button advantage", "Open raising"],
    difficulty: "beginner",
    tags: ["preflop", "in_position", "single_raised"],
  }),
  scenario({
    id: "ps-02",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "CO",
    stakes: "$1/$2",
    heroCards: "7c 6c",
    board: "Kc Tc 2d",
    potSize: 12,
    actionHistory: "Hero called BB preflop. BB checks. Hero?",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 35 },
      { action: "bet", frequency: 65 },
    ],
    preferredAction: "bet",
    explanation:
      "Flush draw with backdoor straight possibilities benefits from betting — builds pot when ahead and generates fold equity. Training solution favors a small c-bet on this coordinated board.",
    concepts: ["Semi-bluff", "Draw equity", "C-betting"],
    difficulty: "intermediate",
    tags: ["flop", "in_position", "single_raised"],
  }),
  scenario({
    id: "ps-03",
    gameType: "NLHE Tournament",
    players: 8,
    effectiveStack: "25bb",
    heroPosition: "SB",
    villainPosition: "BB",
    stakes: "500/1K",
    heroCards: "Qs Jd",
    board: "—",
    potSize: 2.5,
    actionHistory: "Folds to hero in SB. BB has 25bb.",
    availableActions: ["fold", "call", "raise"],
    recommended: [
      { action: "fold", frequency: 15 },
      { action: "call", frequency: 20 },
      { action: "raise", frequency: 65 },
    ],
    preferredAction: "raise",
    explanation:
      "At 25bb effective, QJo from SB vs BB is a standard open-shove or min-raise candidate depending on ICM. Training scenario recommends raising to apply pressure and realize equity.",
    concepts: ["Short stack", "Blind battle", "Push/fold zone"],
    difficulty: "intermediate",
    tags: ["preflop", "out_of_position", "tournament"],
  }),
  scenario({
    id: "ps-04",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "150bb",
    heroPosition: "BB",
    villainPosition: "BTN",
    stakes: "$2/$5",
    heroCards: "9h 9d",
    board: "Ah 7c 3s",
    potSize: 22,
    actionHistory: "BTN opens, hero calls BB. BTN c-bets $15.",
    availableActions: ["fold", "call", "raise"],
    actionLabels: { call: "Call $15", raise: "Raise" },
    recommended: [
      { action: "fold", frequency: 10 },
      { action: "call", frequency: 55 },
      { action: "raise", frequency: 35 },
    ],
    preferredAction: "call",
    explanation:
      "Underpair on an ace-high board has showdown value but limited improvement. Calling keeps bluffs in and avoids building a pot while dominated. Occasional raises are mixed as bluffs.",
    concepts: ["Bluff catching", "Underpair play", "Facing c-bet"],
    difficulty: "intermediate",
    tags: ["flop", "out_of_position", "single_raised"],
  }),
  scenario({
    id: "ps-05",
    gameType: "PLO Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "BTN",
    stakes: "$2/$5",
    heroCards: "As Kh Qd Jc",
    board: "Ts 9h 2c",
    potSize: 45,
    actionHistory: "3-bet pot. Hero 3-bet pre, BB called. BB checks.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 40 },
      { action: "bet", frequency: 60 },
    ],
    preferredAction: "bet",
    explanation:
      "Double-suited Broadway with straight potential on T-9-2 hits this board well. Training scenario favors betting for value/protection in a 3-bet pot.",
    concepts: ["3-bet pot", "PLO connectivity", "Nut potential"],
    difficulty: "advanced",
    tags: ["flop", "in_position", "three_bet", "plo"],
  }),
  scenario({
    id: "ps-06",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "UTG",
    stakes: "$1/$2",
    heroCards: "Ac Ad",
    board: "Kc 7h 2d 9s",
    potSize: 28,
    actionHistory: "Hero opened, one caller. Hero bet flop, caller called. Turn goes check-check.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 20 },
      { action: "bet", frequency: 80 },
    ],
    preferredAction: "bet",
    explanation:
      "Overpair on a dry board after turn checks through still warrants value betting. Size up to charge draws and get value from Kx.",
    concepts: ["Value betting", "Overpair", "Turn barrel"],
    difficulty: "beginner",
    tags: ["turn", "in_position", "single_raised"],
  }),
  scenario({
    id: "ps-07",
    gameType: "NLHE Tournament",
    players: 9,
    effectiveStack: "15bb",
    heroPosition: "CO",
    stakes: "1K/2K",
    heroCards: "Kd Td",
    board: "—",
    potSize: 3.5,
    actionHistory: "Folds to hero.",
    availableActions: ["fold", "raise"],
    recommended: [
      { action: "fold", frequency: 5 },
      { action: "raise", frequency: 95 },
    ],
    preferredAction: "raise",
    explanation: "15bb from CO with KTs is a clear open. Folding is too tight. Training scenario is nearly pure raise.",
    concepts: ["Open raising", "Short stack", "Steal"],
    difficulty: "beginner",
    tags: ["preflop", "in_position", "tournament"],
  }),
  scenario({
    id: "ps-08",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "BTN",
    villainPosition: "SB",
    stakes: "$1/$3",
    heroCards: "5s 4s",
    board: "Js 8h 3c",
    potSize: 18,
    actionHistory: "Hero opened BTN, SB called. SB checks.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 55 },
      { action: "bet", frequency: 45 },
    ],
    preferredAction: "check",
    explanation:
      "Missed flop with backdoor draws — checking back controls pot size. Mixed strategy includes some bluffs but training solution slightly prefers checking.",
    concepts: ["Pot control", "Missed flop", "Position"],
    difficulty: "intermediate",
    tags: ["flop", "in_position", "single_raised"],
  }),
  scenario({
    id: "ps-09",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "MP",
    stakes: "$2/$5",
    heroCards: "Qc Qh",
    board: "Td 9d 4c",
    potSize: 35,
    actionHistory: "Hero opened, BB 3-bet, hero called. BB bets $25 on flop.",
    availableActions: ["fold", "call", "raise"],
    recommended: [
      { action: "fold", frequency: 5 },
      { action: "call", frequency: 70 },
      { action: "raise", frequency: 25 },
    ],
    preferredAction: "call",
    explanation:
      "Overpair in 3-bet pot on a wet board — calling keeps bluffs in and avoids bloating vs better. Some raises for value/protection are mixed.",
    concepts: ["3-bet pot", "Overpair", "Wet board"],
    difficulty: "advanced",
    tags: ["flop", "out_of_position", "three_bet"],
  }),
  scenario({
    id: "ps-10",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "BB",
    stakes: "$1/$2",
    heroCards: "Jh Th",
    board: "Qh 9h 2s 3d 7c",
    potSize: 55,
    actionHistory: "Check-call flop and turn. River blank. Villain bets $40 into $55.",
    availableActions: ["fold", "call", "raise"],
    actionLabels: { call: "Call $40", raise: "Raise to $120" },
    recommended: [
      { action: "fold", frequency: 30 },
      { action: "call", frequency: 55 },
      { action: "raise", frequency: 15 },
    ],
    preferredAction: "call",
    explanation:
      "Missed draw on river — villain's range includes many bluffs from missed draws. Training scenario leans call as bluff-catch; fold is reasonable vs tight players.",
    concepts: ["Bluff catching", "River decision", "Missed draw"],
    difficulty: "advanced",
    tags: ["river", "out_of_position", "single_raised"],
  }),
  scenario({
    id: "ps-11",
    gameType: "NLHE Tournament",
    players: 8,
    effectiveStack: "40bb",
    heroPosition: "BTN",
    stakes: "600/1.2K",
    heroCards: "As 5s",
    board: "—",
    potSize: 3,
    actionHistory: "Folds to hero.",
    availableActions: ["fold", "raise"],
    recommended: [
      { action: "fold", frequency: 8 },
      { action: "raise", frequency: 92 },
    ],
    preferredAction: "raise",
    explanation: "A5s on button with 40bb is a standard steal. High frequency open in training scenario.",
    concepts: ["Steal", "Suited ace", "Position"],
    difficulty: "beginner",
    tags: ["preflop", "in_position", "tournament"],
  }),
  scenario({
    id: "ps-12",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "SB",
    stakes: "$2/$5",
    heroCards: "Kc Qc",
    board: "Ac 8c 4h",
    potSize: 20,
    actionHistory: "BB vs SB limped pot. Hero?",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 45 },
      { action: "bet", frequency: 55 },
    ],
    preferredAction: "bet",
    explanation:
      "King-high with backdoor nut flush draw — small stab generates folds and builds pot when improving.",
    concepts: ["Limped pot", "Semi-bluff", "Backdoor draws"],
    difficulty: "intermediate",
    tags: ["flop", "out_of_position", "single_raised"],
  }),
  scenario({
    id: "ps-13",
    gameType: "PLO Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "CO",
    stakes: "$5/$10",
    heroCards: "Ah Ad Kd Qs",
    board: "Jh Tc 3d",
    potSize: 60,
    actionHistory: "Single raised pot. Hero opened, BB called. BB checks.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 25 },
      { action: "bet", frequency: 75 },
    ],
    preferredAction: "bet",
    explanation:
      "Double Broadway PLO hand connects with straight possibilities. Training scenario bets frequently for value and protection.",
    concepts: ["PLO value", "Straight draws", "C-bet"],
    difficulty: "intermediate",
    tags: ["flop", "in_position", "single_raised", "plo"],
  }),
  scenario({
    id: "ps-14",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "UTG",
    stakes: "$1/$2",
    heroCards: "8s 8c",
    board: "Ah Kd Qc",
    potSize: 15,
    actionHistory: "Hero opened, one caller. Hero?",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 75 },
      { action: "bet", frequency: 25 },
    ],
    preferredAction: "check",
    explanation:
      "Underpair on very coordinated ace-high board — checking is preferred. Occasional small bluffs mixed.",
    concepts: ["Range disadvantage", "Board texture", "Pot control"],
    difficulty: "intermediate",
    tags: ["flop", "in_position", "single_raised"],
  }),
  scenario({
    id: "ps-15",
    gameType: "NLHE Tournament",
    players: 9,
    effectiveStack: "12bb",
    heroPosition: "SB",
    stakes: "800/1.6K",
    heroCards: "7h 6h",
    board: "—",
    potSize: 2.8,
    actionHistory: "Folds to SB. BB covers.",
    availableActions: ["fold", "call", "raise"],
    recommended: [
      { action: "fold", frequency: 20 },
      { action: "call", frequency: 15 },
      { action: "raise", frequency: 65 },
    ],
    preferredAction: "raise",
    explanation: "12bb SB with suited connector — raise/fold strategy applies. Training scenario prefers shove or raise.",
    concepts: ["Push/fold", "SB strategy", "ICM"],
    difficulty: "intermediate",
    tags: ["preflop", "out_of_position", "tournament"],
  }),
  scenario({
    id: "ps-16",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "BTN",
    stakes: "$2/$5",
    heroCards: "Ac Kd",
    board: "Kh 7s 2c 5d",
    potSize: 48,
    actionHistory: "3-bet pot. Hero 3-bet, BB called. Hero bet flop, call. Turn check-check.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 30 },
      { action: "bet", frequency: 70 },
    ],
    preferredAction: "bet",
    explanation: "Top pair top kicker in 3-bet pot — turn bet for value after passive turn action.",
    concepts: ["3-bet pot", "Top pair", "Value betting"],
    difficulty: "intermediate",
    tags: ["turn", "in_position", "three_bet"],
  }),
  scenario({
    id: "ps-17",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "HJ",
    stakes: "$1/$2",
    heroCards: "Td 9d",
    board: "8d 7c 2h",
    potSize: 14,
    actionHistory: "Single raised pot. Hero opened, BB called. BB checks.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 40 },
      { action: "bet", frequency: 60 },
    ],
    preferredAction: "bet",
    explanation: "Open-ended straight draw plus backdoor flush — semi-bluff c-bet is training recommendation.",
    concepts: ["Draw", "Semi-bluff", "C-bet"],
    difficulty: "beginner",
    tags: ["flop", "in_position", "single_raised"],
  }),
  scenario({
    id: "ps-18",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "BB",
    stakes: "$2/$5",
    heroCards: "6c 6d",
    board: "Qc Jh Ts 4h",
    potSize: 40,
    actionHistory: "Defended BB. Check-call flop. Turn check-check. River Qd. Villain bets $30.",
    availableActions: ["fold", "call", "raise"],
    recommended: [
      { action: "fold", frequency: 60 },
      { action: "call", frequency: 30 },
      { action: "raise", frequency: 10 },
    ],
    preferredAction: "fold",
    explanation:
      "Underpair on scary board with river pairing — fold is preferred vs standard bet. Occasional hero calls vs bluffs.",
    concepts: ["Underpair", "River fold", "Board pairing"],
    difficulty: "advanced",
    tags: ["river", "out_of_position", "single_raised"],
  }),
  scenario({
    id: "ps-19",
    gameType: "PLO Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "BTN",
    stakes: "$2/$5",
    heroCards: "Ks Kh 9d 8d",
    board: "Ah 7c 3s",
    potSize: 30,
    actionHistory: "Single raised pot. BB checks.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 50 },
      { action: "bet", frequency: 50 },
    ],
    preferredAction: "check",
    explanation:
      "Kings on ace-high PLO board — range is capped. Training scenario is indifferent; checking is slightly preferred for pot control.",
    concepts: ["PLO pot control", "Overpair", "Ace-high board"],
    difficulty: "advanced",
    tags: ["flop", "in_position", "single_raised", "plo"],
  }),
  scenario({
    id: "ps-20",
    gameType: "NLHE Tournament",
    players: 8,
    effectiveStack: "20bb",
    heroPosition: "BB",
    stakes: "500/1K",
    heroCards: "Ah 2h",
    board: "—",
    potSize: 4.5,
    actionHistory: "BTN min-raises. SB folds. Hero?",
    availableActions: ["fold", "call", "raise"],
    recommended: [
      { action: "fold", frequency: 25 },
      { action: "call", frequency: 35 },
      { action: "raise", frequency: 40 },
    ],
    preferredAction: "raise",
    explanation: "A2s vs BTN open at 20bb — 3-bet shove or call are both viable. Training scenario slightly prefers 3-bet jam.",
    concepts: ["Blind defense", "3-bet shove", "Short stack"],
    difficulty: "intermediate",
    tags: ["preflop", "out_of_position", "tournament"],
  }),
  scenario({
    id: "ps-21",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "CO",
    stakes: "$1/$2",
    heroCards: "Js Jd",
    board: "Tc 9h 8s",
    potSize: 22,
    actionHistory: "Hero opened, BB called. BB checks.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 35 },
      { action: "bet", frequency: 65 },
    ],
    preferredAction: "bet",
    explanation: "Overpair on wet connected board — bet for protection and value vs draws and Tx.",
    concepts: ["Protection bet", "Wet board", "Overpair"],
    difficulty: "beginner",
    tags: ["flop", "in_position", "single_raised"],
  }),
  scenario({
    id: "ps-22",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "BTN",
    stakes: "$2/$5",
    heroCards: "3c 3d",
    board: "Kh Qc 7d 3h",
    potSize: 35,
    actionHistory: "Hero called BTN vs MP open. Check-call flop. Turn MP bets $20, hero?",
    availableActions: ["fold", "call", "raise"],
    actionLabels: { call: "Call $20", raise: "Raise to $75" },
    recommended: [
      { action: "fold", frequency: 5 },
      { action: "call", frequency: 25 },
      { action: "raise", frequency: 70 },
    ],
    preferredAction: "raise",
    explanation: "Set on turn after slow-played flop — raise for value. Training scenario strongly prefers raising.",
    concepts: ["Set mining", "Value raise", "Turn aggression"],
    difficulty: "intermediate",
    tags: ["turn", "in_position", "single_raised"],
  }),
  scenario({
    id: "ps-23",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "UTG",
    stakes: "$2/$5",
    heroCards: "Ad Kc",
    board: "Kd 5s 5c",
    potSize: 18,
    actionHistory: "Hero opened, one caller. Hero?",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 15 },
      { action: "bet", frequency: 85 },
    ],
    preferredAction: "bet",
    explanation: "Top pair top kicker on paired board — clear c-bet for value and protection.",
    concepts: ["C-bet", "Top pair", "Paired board"],
    difficulty: "beginner",
    tags: ["flop", "in_position", "single_raised"],
  }),
  scenario({
    id: "ps-24",
    gameType: "PLO Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "SB",
    stakes: "$5/$10",
    heroCards: "Qh Jh Th 9h",
    board: "Ah Kc 2d",
    potSize: 50,
    actionHistory: "3-bet pot. Hero 3-bet from SB, BB called. BB checks.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 55 },
      { action: "bet", frequency: 45 },
    ],
    preferredAction: "check",
    explanation:
      "Wrap + flush draw potential but ace on board favors caller's range in 3-bet pot. Training scenario slightly prefers checking.",
    concepts: ["3-bet pot", "PLO range", "Board favorability"],
    difficulty: "advanced",
    tags: ["flop", "out_of_position", "three_bet", "plo"],
  }),
  scenario({
    id: "ps-25",
    gameType: "NLHE Tournament",
    players: 9,
    effectiveStack: "8bb",
    heroPosition: "UTG",
    stakes: "1K/2K",
    heroCards: "Ac Tc",
    board: "—",
    potSize: 2.5,
    actionHistory: "Hero first to act.",
    availableActions: ["fold", "raise"],
    recommended: [
      { action: "fold", frequency: 10 },
      { action: "raise", frequency: 90 },
    ],
    preferredAction: "raise",
    explanation: "8bb UTG with ATs — push/fold territory. Training scenario is nearly pure shove/open.",
    concepts: ["Push/fold", "Short stack", "UTG shove"],
    difficulty: "beginner",
    tags: ["preflop", "out_of_position", "tournament"],
  }),
  scenario({
    id: "ps-26",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "BB",
    stakes: "$1/$2",
    heroCards: "As 4s",
    board: "Ks 7s 2c",
    potSize: 12,
    actionHistory: "BTN opened, hero defended. BTN c-bets $8.",
    availableActions: ["fold", "call", "raise"],
    recommended: [
      { action: "fold", frequency: 15 },
      { action: "call", frequency: 60 },
      { action: "raise", frequency: 25 },
    ],
    preferredAction: "call",
    explanation: "Nut flush draw — calling is standard. Some raises as semi-bluff mixed in training scenario.",
    concepts: ["Flush draw", "Facing c-bet", "Implied odds"],
    difficulty: "beginner",
    tags: ["flop", "out_of_position", "single_raised"],
  }),
  scenario({
    id: "ps-27",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "MP",
    stakes: "$2/$5",
    heroCards: "Kh Qh",
    board: "Ah Jh Tc",
    potSize: 25,
    actionHistory: "Single raised pot. Hero opened, BB called. BB checks.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 20 },
      { action: "bet", frequency: 80 },
    ],
    preferredAction: "bet",
    explanation: "Broadway wrap with flush draw — powerful semi-bluff/value bet. Training scenario bets frequently.",
    concepts: ["Combo draw", "Semi-bluff", "Nut potential"],
    difficulty: "intermediate",
    tags: ["flop", "in_position", "single_raised"],
  }),
  scenario({
    id: "ps-28",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "BTN",
    stakes: "$1/$2",
    heroCards: "9c 8c",
    board: "7h 6d 2s 9h Kh",
    potSize: 42,
    actionHistory: "Hero hit middle pair on turn, bet turn, villain called. River pairs board. Villain checks.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 65 },
      { action: "bet", frequency: 35 },
    ],
    preferredAction: "check",
    explanation:
      "Middle pair on paired river — pot control preferred. Thin value bets mixed but checking is training recommendation.",
    concepts: ["Thin value", "River check", "Pot control"],
    difficulty: "advanced",
    tags: ["river", "in_position", "single_raised"],
  }),
  scenario({
    id: "ps-29",
    gameType: "NLHE Tournament",
    players: 8,
    effectiveStack: "30bb",
    heroPosition: "HJ",
    stakes: "400/800",
    heroCards: "Qh Qd",
    board: "—",
    potSize: 2.5,
    actionHistory: "UTG opens 2.5x. Folds to hero.",
    availableActions: ["fold", "call", "raise"],
    recommended: [
      { action: "fold", frequency: 5 },
      { action: "call", frequency: 25 },
      { action: "raise", frequency: 70 },
    ],
    preferredAction: "raise",
    explanation: "QQ vs UTG open — 3-bet for value is training recommendation. Flatting is mixed for deception.",
    concepts: ["3-bet for value", "Premium pairs", "Tournament"],
    difficulty: "intermediate",
    tags: ["preflop", "in_position", "three_bet", "tournament"],
  }),
  scenario({
    id: "ps-30",
    gameType: "NLHE Cash",
    players: 6,
    effectiveStack: "100bb",
    heroPosition: "SB",
    stakes: "$2/$5",
    heroCards: "2d 2c",
    board: "Ah Kc Qd Jh Tc",
    potSize: 80,
    actionHistory: "4-bet pot. River completes broadway. Villain checks.",
    availableActions: ["check", "bet"],
    recommended: [
      { action: "check", frequency: 90 },
      { action: "bet", frequency: 10 },
    ],
    preferredAction: "check",
    explanation:
      "Deuces on broadway runout — no showdown value vs checking range. Pure check in training scenario.",
    concepts: ["Bluff catching", "Showdown value", "4-bet pot"],
    difficulty: "advanced",
    tags: ["river", "out_of_position", "three_bet"],
  }),
];

export function getScenarioById(id: string): PokerScenario | undefined {
  return POKER_SCENARIOS.find((s) => s.id === id);
}

export function getRandomScenario(excludeId?: string): PokerScenario {
  const pool = POKER_SCENARIOS.filter((s) => s.id !== excludeId);
  return pool[Math.floor(Math.random() * pool.length)] || POKER_SCENARIOS[0];
}

export function getScenariosByDifficulty(difficulty?: string): PokerScenario[] {
  if (!difficulty || difficulty === "all") return POKER_SCENARIOS;
  return POKER_SCENARIOS.filter((s) => s.difficulty === difficulty);
}
